package com.liferun.qb;

public enum QBQueries {
	QB_QUERY_AUTHORIZE_APP,
    QB_QUERY_GET_ALL_USERS,
    QB_QUERY_CREATE_QB_USER,
    QB_QUERY_SIGN_IN_QB_USER,
    QB_QUERY_SIGN_UP_QB_USER,
    QB_QUERY_LOG_OUT_QB_USER,
    QB_QUERY_UPDATE_QB_USER,
    QB_QUERY_DELETE_QB_USER,
    SIGN_IN,
    CREATE_EVENT,
    GET_EVENT_LIST
}
